[package]
name = "de"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
readme = "README.md"
repository = "https://github.com/DigitalExtinction/Game"

[dependencies]
# DE
de_objects = { path = "crates/objects", version = "0.1.0-dev" }
de_index = { path = "crates/index", version = "0.1.0-dev" }
de_pathing = { path = "crates/pathing", version = "0.1.0-dev" }
de_movement = { path = "crates/movement", version = "0.1.0-dev" }
de_controller = { path = "crates/controller", version = "0.1.0-dev" }
de_camera = { path = "crates/camera", version = "0.1.0-dev" }
de_game = { path = "crates/game", version = "0.1.0-dev" }

# Other
bevy = "0.7.0"

[workspace]
members = ["crates/*"]
