[package]
name = "de"
version = "0.1.0"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
readme = "README.md"
repository = "https://github.com/Indy2222/Digital-Extinction"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "^0.6.1"
anyhow = "^1.0"
tar = "0.4"
serde = "1.0"
serde_json = "1.0"
glam = "^0.20.2"
