[package]
name = "de"
version = "0.1.0"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
readme = "README.md"
repository = "https://github.com/Indy2222/Digital-Extinction"

[dependencies]
de_game = { path = "crates/game" }

[workspace]
members = ["crates/*"]
