[package]
name = "de"
version = "0.1.0"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
readme = "README.md"
repository = "https://github.com/Indy2222/Digital-Extinction"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/Indy2222/bevy", branch = "de" }
anyhow = "^1.0"
tar = "0.4"
serde = "1.0"
serde_json = "1.0"
glam = "^0.20.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "ray_intersection"
harness = false
