[package]
name = "de_uom"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/DigitalExtinction/Game"
keywords = ["DigitalExtinction", "gamedev", "game", "units"]
homepage = "https://de-game.org/"
description = "Type safe units of measurements."
license = "GPL-3.0"
categories = ["games"]

[dependencies]
thiserror = "1.0"

[dev-dependencies]
approx = "0.5.1"
