[package]
name = "de_ui"
description = "2D game UI for Digital Extinction."

version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
# DE
de_core = { path = "../core", version = "0.1.0-dev" }

# Other
bevy = "0.8"
iyes_loopless = "0.7"
