[package]
name = "de_index"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/DigitalExtinction/Game"
keywords = ["DigitalExtinction", "gamedev", "game", "bevy", "3d"]
homepage = "https://de-game.org/"
description = "Spatial index of all solid entities in Digital Extinction."
license = "GPL-3.0"
categories = ["games"]

[dependencies]
# DE
de_core = { path = "../core", version = "0.1.0-dev" }
de_objects = { path = "../objects", version = "0.1.0-dev" }

# Other
bevy = "0.8"
glam = "0.21"
iyes_loopless = "0.7"
parry3d = "0.9.0"
parry2d = { git = "https://github.com/Indy2222/parry", branch = "feature/dilation" }
ahash = "0.7.6"
nalgebra = { version = "0.31.0", features = ["convert-glam021"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "ray"
harness = false
