[package]
name = "de_camera"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/DigitalExtinction/Game"
keywords = ["DigitalExtinction", "gamedev", "game", "bevy", "3d"]
homepage = "https://de-game.org/"
description = "Camera related functionality in Digital Extinction."
license = "GPL-3.0"
categories = ["games"]

[dependencies]
# DE
de_uom = { path = "../uom", version = "0.1.0-dev" }
de_core = { path = "../core", version = "0.1.0-dev" }
de_map = { path = "../map", version = "0.1.0-dev" }
de_terrain = { path = "../terrain", version = "0.1.0-dev" }

# Other
bevy = "0.8"
iyes_loopless = "0.7"
parry3d = "0.9.0"
