[package]
name = "de_map"
version = "0.1.0"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/Indy2222/Digital-Extinction"

[dependencies]
de_objects = { path = "../objects" }
bevy = "0.7"
glam = "0.20.2"
serde = "1.0"
serde_json = "1.0"
tar = "0.4"
thiserror = "1.0"
