[package]
name = "de_tools"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/DigitalExtinction/Game"
keywords = ["DigitalExtinction", "gamedev", "game", "bevy", "3d"]
homepage = "https://de-game.org/"
description = "Tools and utilities for Digital Extinction developers, and artists."
license = "GPL-3.0"
categories = ["games"]

[dependencies]
gltf = "1.0"
parry3d = "0.9.0"
clap = { version = "3.2.6", features = ["derive"] }
