[package]
name = "de_terrain"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/DigitalExtinction/Game"

[dependencies]
# DE
de_map = { path = "../map", version = "0.1.0-dev" }

# Other
bevy = "0.8"
glam = "0.21"
parry3d = "0.9.0"
