[package]
name = "de_core"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/Indy2222/Digital-Extinction"

[dependencies]
bevy = "0.7"
serde = "1.0"
