[package]
name = "de_core"
description = "Various simple core utilities, structs, and so on for Digital Extinction."

version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bevy = "0.8"
iyes_loopless = "0.7"
iyes_progress = { version = "0.4", features = [ "iyes_loopless" ] }
glam = "0.21"
nalgebra = { version = "0.31.0", features = ["convert-glam021"] }
parry2d = { git = "https://github.com/Indy2222/parry", branch = "feature/dilation" }
parry3d = "0.9.0"
enum-map = "2.3.0"
