[package]
name = "de_core"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/DigitalExtinction/Game"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bevy = "0.7.0"
iyes_loopless = "0.5.1"
iyes_progress = { version = "0.3.0", features = [ "iyes_loopless" ] }
glam = "0.20.2"
nalgebra = { version = "0.31.0", features = ["convert-glam020"] }
parry2d = { git = "https://github.com/Indy2222/parry", branch = "feature/dilation" }
parry3d = "0.9.0"
