name: Rust

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Test Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update
      - run: cargo fmt --version
      - run: cargo fmt -- --check
